/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedIndexRouteImport } from './routes/embed.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmbedAccountIdRouteImport } from './routes/embed.$accountId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin.templates.index'
import { Route as EmbedAccountAccountIdRouteImport } from './routes/embed.account.$accountId'
import { Route as AdminTemplatesTemplateIdRouteImport } from './routes/admin.templates.$templateId'
import { Route as AdminAccountAccountIdRouteImport } from './routes/admin.account.$accountId'
import { Route as EmbedAccountAccountIdIndexRouteImport } from './routes/embed.account.$accountId.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIndexRoute = EmbedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedAccountIdRoute = EmbedAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => EmbedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedAccountAccountIdRoute = EmbedAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => EmbedRoute,
} as any)
const AdminTemplatesTemplateIdRoute =
  AdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAccountAccountIdRoute = AdminAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedAccountAccountIdIndexRoute =
  EmbedAccountAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/embed': typeof EmbedRouteWithChildren
  '/login': typeof LoginRoute
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/admin/': typeof AdminIndexRoute
  '/embed/': typeof EmbedIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/embed': typeof EmbedIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/admin/': typeof AdminIndexRoute
  '/embed/': typeof EmbedIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/embed'
    | '/login'
    | '/embed/$accountId'
    | '/admin/'
    | '/embed/'
    | '/admin/account/$accountId'
    | '/admin/templates/$templateId'
    | '/embed/account/$accountId'
    | '/admin/templates/'
    | '/embed/account/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/embed/$accountId'
    | '/embed'
    | '/admin/account/$accountId'
    | '/admin/templates/$templateId'
    | '/admin/templates'
    | '/embed/account/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/embed'
    | '/login'
    | '/_authenticated/admin'
    | '/embed/$accountId'
    | '/admin/'
    | '/embed/'
    | '/admin/account/$accountId'
    | '/admin/templates/$templateId'
    | '/embed/account/$accountId'
    | '/admin/templates/'
    | '/embed/account/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  EmbedRoute: typeof EmbedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/': {
      id: '/embed/'
      path: '/'
      fullPath: '/embed/'
      preLoaderRoute: typeof EmbedIndexRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/$accountId': {
      id: '/embed/$accountId'
      path: '/$accountId'
      fullPath: '/embed/$accountId'
      preLoaderRoute: typeof EmbedAccountIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/account/$accountId': {
      id: '/embed/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/embed/account/$accountId'
      preLoaderRoute: typeof EmbedAccountAccountIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/admin/templates/$templateId': {
      id: '/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account/$accountId': {
      id: '/admin/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/admin/account/$accountId'
      preLoaderRoute: typeof AdminAccountAccountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/account/$accountId/': {
      id: '/embed/account/$accountId/'
      path: '/'
      fullPath: '/embed/account/$accountId/'
      preLoaderRoute: typeof EmbedAccountAccountIdIndexRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountAccountIdRoute: typeof AdminAccountAccountIdRoute
  AdminTemplatesTemplateIdRoute: typeof AdminTemplatesTemplateIdRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountAccountIdRoute: AdminAccountAccountIdRoute,
  AdminTemplatesTemplateIdRoute: AdminTemplatesTemplateIdRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmbedAccountAccountIdRouteChildren {
  EmbedAccountAccountIdIndexRoute: typeof EmbedAccountAccountIdIndexRoute
}

const EmbedAccountAccountIdRouteChildren: EmbedAccountAccountIdRouteChildren = {
  EmbedAccountAccountIdIndexRoute: EmbedAccountAccountIdIndexRoute,
}

const EmbedAccountAccountIdRouteWithChildren =
  EmbedAccountAccountIdRoute._addFileChildren(
    EmbedAccountAccountIdRouteChildren,
  )

interface EmbedRouteChildren {
  EmbedAccountIdRoute: typeof EmbedAccountIdRoute
  EmbedIndexRoute: typeof EmbedIndexRoute
  EmbedAccountAccountIdRoute: typeof EmbedAccountAccountIdRouteWithChildren
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedAccountIdRoute: EmbedAccountIdRoute,
  EmbedIndexRoute: EmbedIndexRoute,
  EmbedAccountAccountIdRoute: EmbedAccountAccountIdRouteWithChildren,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  EmbedRoute: EmbedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
