/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedIndexRouteImport } from './routes/embed.index'
import { Route as EmbedAccountIdRouteImport } from './routes/embed.$accountId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as EmbedAccountAccountIdRouteImport } from './routes/embed.account.$accountId'
import { Route as EmbedAccountAccountIdIndexRouteImport } from './routes/embed.account.$accountId.index'
import { Route as ApiPublicCronWarmupRouteImport } from './routes/api/public/cron/warmup'
import { Route as ApiPublicCronQueueRouteImport } from './routes/api/public/cron/queue'
import { Route as ApiPublicCronFollowupRouteImport } from './routes/api/public/cron/followup'
import { Route as AuthenticatedAdminAccountAccountIdRouteImport } from './routes/_authenticated.admin.account.$accountId'
import { Route as ApiPublicWebhookHelenaAccountIdRouteImport } from './routes/api/public/webhook/helena/$accountId'
import { Route as ApiPublicWebhookAutomacoesFufFinanceiroRouteImport } from './routes/api/public/webhook/automacoes/fuf-financeiro'
import { Route as ApiPublicWebhookAutomacoesFaltososRouteImport } from './routes/api/public/webhook/automacoes/faltosos'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth/google/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIndexRoute = EmbedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedAccountIdRoute = EmbedAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => EmbedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const EmbedAccountAccountIdRoute = EmbedAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedAccountAccountIdIndexRoute =
  EmbedAccountAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const ApiPublicCronWarmupRoute = ApiPublicCronWarmupRouteImport.update({
  id: '/api/public/cron/warmup',
  path: '/api/public/cron/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronQueueRoute = ApiPublicCronQueueRouteImport.update({
  id: '/api/public/cron/queue',
  path: '/api/public/cron/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFollowupRoute = ApiPublicCronFollowupRouteImport.update({
  id: '/api/public/cron/followup',
  path: '/api/public/cron/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAccountAccountIdRoute =
  AuthenticatedAdminAccountAccountIdRouteImport.update({
    id: '/account/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhookHelenaAccountIdRoute =
  ApiPublicWebhookHelenaAccountIdRouteImport.update({
    id: '/api/public/webhook/helena/$accountId',
    path: '/api/public/webhook/helena/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookAutomacoesFufFinanceiroRoute =
  ApiPublicWebhookAutomacoesFufFinanceiroRouteImport.update({
    id: '/api/public/webhook/automacoes/fuf-financeiro',
    path: '/api/public/webhook/automacoes/fuf-financeiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookAutomacoesFaltososRoute =
  ApiPublicWebhookAutomacoesFaltososRouteImport.update({
    id: '/api/public/webhook/automacoes/faltosos',
    path: '/api/public/webhook/automacoes/faltosos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleCallbackRoute =
  ApiPublicAuthGoogleCallbackRouteImport.update({
    id: '/api/public/auth/google/callback',
    path: '/api/public/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/embed/': typeof EmbedIndexRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/account/$accountId': typeof AuthenticatedAdminAccountAccountIdRoute
  '/api/public/cron/followup': typeof ApiPublicCronFollowupRoute
  '/api/public/cron/queue': typeof ApiPublicCronQueueRoute
  '/api/public/cron/warmup': typeof ApiPublicCronWarmupRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/webhook/automacoes/faltosos': typeof ApiPublicWebhookAutomacoesFaltososRoute
  '/api/public/webhook/automacoes/fuf-financeiro': typeof ApiPublicWebhookAutomacoesFufFinanceiroRoute
  '/api/public/webhook/helena/$accountId': typeof ApiPublicWebhookHelenaAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/embed': typeof EmbedIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/account/$accountId': typeof AuthenticatedAdminAccountAccountIdRoute
  '/api/public/cron/followup': typeof ApiPublicCronFollowupRoute
  '/api/public/cron/queue': typeof ApiPublicCronQueueRoute
  '/api/public/cron/warmup': typeof ApiPublicCronWarmupRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/webhook/automacoes/faltosos': typeof ApiPublicWebhookAutomacoesFaltososRoute
  '/api/public/webhook/automacoes/fuf-financeiro': typeof ApiPublicWebhookAutomacoesFufFinanceiroRoute
  '/api/public/webhook/helena/$accountId': typeof ApiPublicWebhookHelenaAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/embed/$accountId': typeof EmbedAccountIdRoute
  '/embed/': typeof EmbedIndexRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/account/$accountId': typeof AuthenticatedAdminAccountAccountIdRoute
  '/api/public/cron/followup': typeof ApiPublicCronFollowupRoute
  '/api/public/cron/queue': typeof ApiPublicCronQueueRoute
  '/api/public/cron/warmup': typeof ApiPublicCronWarmupRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/webhook/automacoes/faltosos': typeof ApiPublicWebhookAutomacoesFaltososRoute
  '/api/public/webhook/automacoes/fuf-financeiro': typeof ApiPublicWebhookAutomacoesFufFinanceiroRoute
  '/api/public/webhook/helena/$accountId': typeof ApiPublicWebhookHelenaAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/login'
    | '/admin'
    | '/embed/$accountId'
    | '/embed/'
    | '/embed/account/$accountId'
    | '/admin/'
    | '/admin/account/$accountId'
    | '/api/public/cron/followup'
    | '/api/public/cron/queue'
    | '/api/public/cron/warmup'
    | '/embed/account/$accountId/'
    | '/api/public/auth/google/callback'
    | '/api/public/webhook/automacoes/faltosos'
    | '/api/public/webhook/automacoes/fuf-financeiro'
    | '/api/public/webhook/helena/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/embed/$accountId'
    | '/embed'
    | '/admin'
    | '/admin/account/$accountId'
    | '/api/public/cron/followup'
    | '/api/public/cron/queue'
    | '/api/public/cron/warmup'
    | '/embed/account/$accountId'
    | '/api/public/auth/google/callback'
    | '/api/public/webhook/automacoes/faltosos'
    | '/api/public/webhook/automacoes/fuf-financeiro'
    | '/api/public/webhook/helena/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/embed'
    | '/login'
    | '/_authenticated/admin'
    | '/embed/$accountId'
    | '/embed/'
    | '/embed/account/$accountId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/account/$accountId'
    | '/api/public/cron/followup'
    | '/api/public/cron/queue'
    | '/api/public/cron/warmup'
    | '/embed/account/$accountId/'
    | '/api/public/auth/google/callback'
    | '/api/public/webhook/automacoes/faltosos'
    | '/api/public/webhook/automacoes/fuf-financeiro'
    | '/api/public/webhook/helena/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EmbedRoute: typeof EmbedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronFollowupRoute: typeof ApiPublicCronFollowupRoute
  ApiPublicCronQueueRoute: typeof ApiPublicCronQueueRoute
  ApiPublicCronWarmupRoute: typeof ApiPublicCronWarmupRoute
  ApiPublicAuthGoogleCallbackRoute: typeof ApiPublicAuthGoogleCallbackRoute
  ApiPublicWebhookAutomacoesFaltososRoute: typeof ApiPublicWebhookAutomacoesFaltososRoute
  ApiPublicWebhookAutomacoesFufFinanceiroRoute: typeof ApiPublicWebhookAutomacoesFufFinanceiroRoute
  ApiPublicWebhookHelenaAccountIdRoute: typeof ApiPublicWebhookHelenaAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/': {
      id: '/embed/'
      path: '/'
      fullPath: '/embed/'
      preLoaderRoute: typeof EmbedIndexRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/embed/$accountId': {
      id: '/embed/$accountId'
      path: '/$accountId'
      fullPath: '/embed/$accountId'
      preLoaderRoute: typeof EmbedAccountIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/embed/account/$accountId': {
      id: '/embed/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/embed/account/$accountId'
      preLoaderRoute: typeof EmbedAccountAccountIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/embed/account/$accountId/': {
      id: '/embed/account/$accountId/'
      path: '/'
      fullPath: '/embed/account/$accountId/'
      preLoaderRoute: typeof EmbedAccountAccountIdIndexRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/api/public/cron/warmup': {
      id: '/api/public/cron/warmup'
      path: '/api/public/cron/warmup'
      fullPath: '/api/public/cron/warmup'
      preLoaderRoute: typeof ApiPublicCronWarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/queue': {
      id: '/api/public/cron/queue'
      path: '/api/public/cron/queue'
      fullPath: '/api/public/cron/queue'
      preLoaderRoute: typeof ApiPublicCronQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/followup': {
      id: '/api/public/cron/followup'
      path: '/api/public/cron/followup'
      fullPath: '/api/public/cron/followup'
      preLoaderRoute: typeof ApiPublicCronFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/account/$accountId': {
      id: '/_authenticated/admin/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/admin/account/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminAccountAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhook/helena/$accountId': {
      id: '/api/public/webhook/helena/$accountId'
      path: '/api/public/webhook/helena/$accountId'
      fullPath: '/api/public/webhook/helena/$accountId'
      preLoaderRoute: typeof ApiPublicWebhookHelenaAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/automacoes/fuf-financeiro': {
      id: '/api/public/webhook/automacoes/fuf-financeiro'
      path: '/api/public/webhook/automacoes/fuf-financeiro'
      fullPath: '/api/public/webhook/automacoes/fuf-financeiro'
      preLoaderRoute: typeof ApiPublicWebhookAutomacoesFufFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/automacoes/faltosos': {
      id: '/api/public/webhook/automacoes/faltosos'
      path: '/api/public/webhook/automacoes/faltosos'
      fullPath: '/api/public/webhook/automacoes/faltosos'
      preLoaderRoute: typeof ApiPublicWebhookAutomacoesFaltososRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/callback': {
      id: '/api/public/auth/google/callback'
      path: '/api/public/auth/google/callback'
      fullPath: '/api/public/auth/google/callback'
      preLoaderRoute: typeof ApiPublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAccountAccountIdRoute: typeof AuthenticatedAdminAccountAccountIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAccountAccountIdRoute:
    AuthenticatedAdminAccountAccountIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EmbedAccountAccountIdRouteChildren {
  EmbedAccountAccountIdIndexRoute: typeof EmbedAccountAccountIdIndexRoute
}

const EmbedAccountAccountIdRouteChildren: EmbedAccountAccountIdRouteChildren = {
  EmbedAccountAccountIdIndexRoute: EmbedAccountAccountIdIndexRoute,
}

const EmbedAccountAccountIdRouteWithChildren =
  EmbedAccountAccountIdRoute._addFileChildren(
    EmbedAccountAccountIdRouteChildren,
  )

interface EmbedRouteChildren {
  EmbedAccountIdRoute: typeof EmbedAccountIdRoute
  EmbedIndexRoute: typeof EmbedIndexRoute
  EmbedAccountAccountIdRoute: typeof EmbedAccountAccountIdRouteWithChildren
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedAccountIdRoute: EmbedAccountIdRoute,
  EmbedIndexRoute: EmbedIndexRoute,
  EmbedAccountAccountIdRoute: EmbedAccountAccountIdRouteWithChildren,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EmbedRoute: EmbedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronFollowupRoute: ApiPublicCronFollowupRoute,
  ApiPublicCronQueueRoute: ApiPublicCronQueueRoute,
  ApiPublicCronWarmupRoute: ApiPublicCronWarmupRoute,
  ApiPublicAuthGoogleCallbackRoute: ApiPublicAuthGoogleCallbackRoute,
  ApiPublicWebhookAutomacoesFaltososRoute:
    ApiPublicWebhookAutomacoesFaltososRoute,
  ApiPublicWebhookAutomacoesFufFinanceiroRoute:
    ApiPublicWebhookAutomacoesFufFinanceiroRoute,
  ApiPublicWebhookHelenaAccountIdRoute: ApiPublicWebhookHelenaAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
