/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmbedAccountAccountIdRouteImport } from './routes/embed.account.$accountId'
import { Route as AdminAccountAccountIdRouteImport } from './routes/admin.account.$accountId'
import { Route as EmbedAccountAccountIdIndexRouteImport } from './routes/embed.account.$accountId.index'
import { Route as EmbedAccountAccountIdWarmupRouteImport } from './routes/embed.account.$accountId.warmup'
import { Route as EmbedAccountAccountIdOverviewRouteImport } from './routes/embed.account.$accountId.overview'
import { Route as EmbedAccountAccountIdMediaRouteImport } from './routes/embed.account.$accountId.media'
import { Route as EmbedAccountAccountIdMainAgentRouteImport } from './routes/embed.account.$accountId.main-agent'
import { Route as EmbedAccountAccountIdLogsRouteImport } from './routes/embed.account.$accountId.logs'
import { Route as EmbedAccountAccountIdIntegrationsRouteImport } from './routes/embed.account.$accountId.integrations'
import { Route as EmbedAccountAccountIdFollowupRouteImport } from './routes/embed.account.$accountId.followup'
import { Route as EmbedAccountAccountIdConversationsRouteImport } from './routes/embed.account.$accountId.conversations'
import { Route as EmbedAccountAccountIdAutomationsRouteImport } from './routes/embed.account.$accountId.automations'

const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedAccountAccountIdRoute = EmbedAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => EmbedRoute,
} as any)
const AdminAccountAccountIdRoute = AdminAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedAccountAccountIdIndexRoute =
  EmbedAccountAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdWarmupRoute =
  EmbedAccountAccountIdWarmupRouteImport.update({
    id: '/warmup',
    path: '/warmup',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdOverviewRoute =
  EmbedAccountAccountIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdMediaRoute =
  EmbedAccountAccountIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdMainAgentRoute =
  EmbedAccountAccountIdMainAgentRouteImport.update({
    id: '/main-agent',
    path: '/main-agent',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdLogsRoute =
  EmbedAccountAccountIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdIntegrationsRoute =
  EmbedAccountAccountIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdFollowupRoute =
  EmbedAccountAccountIdFollowupRouteImport.update({
    id: '/followup',
    path: '/followup',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdConversationsRoute =
  EmbedAccountAccountIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)
const EmbedAccountAccountIdAutomationsRoute =
  EmbedAccountAccountIdAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => EmbedAccountAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/embed/account/$accountId/automations': typeof EmbedAccountAccountIdAutomationsRoute
  '/embed/account/$accountId/conversations': typeof EmbedAccountAccountIdConversationsRoute
  '/embed/account/$accountId/followup': typeof EmbedAccountAccountIdFollowupRoute
  '/embed/account/$accountId/integrations': typeof EmbedAccountAccountIdIntegrationsRoute
  '/embed/account/$accountId/logs': typeof EmbedAccountAccountIdLogsRoute
  '/embed/account/$accountId/main-agent': typeof EmbedAccountAccountIdMainAgentRoute
  '/embed/account/$accountId/media': typeof EmbedAccountAccountIdMediaRoute
  '/embed/account/$accountId/overview': typeof EmbedAccountAccountIdOverviewRoute
  '/embed/account/$accountId/warmup': typeof EmbedAccountAccountIdWarmupRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/embed/account/$accountId/automations': typeof EmbedAccountAccountIdAutomationsRoute
  '/embed/account/$accountId/conversations': typeof EmbedAccountAccountIdConversationsRoute
  '/embed/account/$accountId/followup': typeof EmbedAccountAccountIdFollowupRoute
  '/embed/account/$accountId/integrations': typeof EmbedAccountAccountIdIntegrationsRoute
  '/embed/account/$accountId/logs': typeof EmbedAccountAccountIdLogsRoute
  '/embed/account/$accountId/main-agent': typeof EmbedAccountAccountIdMainAgentRoute
  '/embed/account/$accountId/media': typeof EmbedAccountAccountIdMediaRoute
  '/embed/account/$accountId/overview': typeof EmbedAccountAccountIdOverviewRoute
  '/embed/account/$accountId/warmup': typeof EmbedAccountAccountIdWarmupRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/embed/account/$accountId': typeof EmbedAccountAccountIdRouteWithChildren
  '/embed/account/$accountId/automations': typeof EmbedAccountAccountIdAutomationsRoute
  '/embed/account/$accountId/conversations': typeof EmbedAccountAccountIdConversationsRoute
  '/embed/account/$accountId/followup': typeof EmbedAccountAccountIdFollowupRoute
  '/embed/account/$accountId/integrations': typeof EmbedAccountAccountIdIntegrationsRoute
  '/embed/account/$accountId/logs': typeof EmbedAccountAccountIdLogsRoute
  '/embed/account/$accountId/main-agent': typeof EmbedAccountAccountIdMainAgentRoute
  '/embed/account/$accountId/media': typeof EmbedAccountAccountIdMediaRoute
  '/embed/account/$accountId/overview': typeof EmbedAccountAccountIdOverviewRoute
  '/embed/account/$accountId/warmup': typeof EmbedAccountAccountIdWarmupRoute
  '/embed/account/$accountId/': typeof EmbedAccountAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/embed'
    | '/admin/'
    | '/admin/account/$accountId'
    | '/embed/account/$accountId'
    | '/embed/account/$accountId/automations'
    | '/embed/account/$accountId/conversations'
    | '/embed/account/$accountId/followup'
    | '/embed/account/$accountId/integrations'
    | '/embed/account/$accountId/logs'
    | '/embed/account/$accountId/main-agent'
    | '/embed/account/$accountId/media'
    | '/embed/account/$accountId/overview'
    | '/embed/account/$accountId/warmup'
    | '/embed/account/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/admin'
    | '/admin/account/$accountId'
    | '/embed/account/$accountId/automations'
    | '/embed/account/$accountId/conversations'
    | '/embed/account/$accountId/followup'
    | '/embed/account/$accountId/integrations'
    | '/embed/account/$accountId/logs'
    | '/embed/account/$accountId/main-agent'
    | '/embed/account/$accountId/media'
    | '/embed/account/$accountId/overview'
    | '/embed/account/$accountId/warmup'
    | '/embed/account/$accountId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/embed'
    | '/admin/'
    | '/admin/account/$accountId'
    | '/embed/account/$accountId'
    | '/embed/account/$accountId/automations'
    | '/embed/account/$accountId/conversations'
    | '/embed/account/$accountId/followup'
    | '/embed/account/$accountId/integrations'
    | '/embed/account/$accountId/logs'
    | '/embed/account/$accountId/main-agent'
    | '/embed/account/$accountId/media'
    | '/embed/account/$accountId/overview'
    | '/embed/account/$accountId/warmup'
    | '/embed/account/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmbedRoute: typeof EmbedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/account/$accountId': {
      id: '/embed/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/embed/account/$accountId'
      preLoaderRoute: typeof EmbedAccountAccountIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/admin/account/$accountId': {
      id: '/admin/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/admin/account/$accountId'
      preLoaderRoute: typeof AdminAccountAccountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/account/$accountId/': {
      id: '/embed/account/$accountId/'
      path: '/'
      fullPath: '/embed/account/$accountId/'
      preLoaderRoute: typeof EmbedAccountAccountIdIndexRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/warmup': {
      id: '/embed/account/$accountId/warmup'
      path: '/warmup'
      fullPath: '/embed/account/$accountId/warmup'
      preLoaderRoute: typeof EmbedAccountAccountIdWarmupRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/overview': {
      id: '/embed/account/$accountId/overview'
      path: '/overview'
      fullPath: '/embed/account/$accountId/overview'
      preLoaderRoute: typeof EmbedAccountAccountIdOverviewRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/media': {
      id: '/embed/account/$accountId/media'
      path: '/media'
      fullPath: '/embed/account/$accountId/media'
      preLoaderRoute: typeof EmbedAccountAccountIdMediaRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/main-agent': {
      id: '/embed/account/$accountId/main-agent'
      path: '/main-agent'
      fullPath: '/embed/account/$accountId/main-agent'
      preLoaderRoute: typeof EmbedAccountAccountIdMainAgentRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/logs': {
      id: '/embed/account/$accountId/logs'
      path: '/logs'
      fullPath: '/embed/account/$accountId/logs'
      preLoaderRoute: typeof EmbedAccountAccountIdLogsRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/integrations': {
      id: '/embed/account/$accountId/integrations'
      path: '/integrations'
      fullPath: '/embed/account/$accountId/integrations'
      preLoaderRoute: typeof EmbedAccountAccountIdIntegrationsRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/followup': {
      id: '/embed/account/$accountId/followup'
      path: '/followup'
      fullPath: '/embed/account/$accountId/followup'
      preLoaderRoute: typeof EmbedAccountAccountIdFollowupRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/conversations': {
      id: '/embed/account/$accountId/conversations'
      path: '/conversations'
      fullPath: '/embed/account/$accountId/conversations'
      preLoaderRoute: typeof EmbedAccountAccountIdConversationsRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
    '/embed/account/$accountId/automations': {
      id: '/embed/account/$accountId/automations'
      path: '/automations'
      fullPath: '/embed/account/$accountId/automations'
      preLoaderRoute: typeof EmbedAccountAccountIdAutomationsRouteImport
      parentRoute: typeof EmbedAccountAccountIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountAccountIdRoute: typeof AdminAccountAccountIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountAccountIdRoute: AdminAccountAccountIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmbedAccountAccountIdRouteChildren {
  EmbedAccountAccountIdAutomationsRoute: typeof EmbedAccountAccountIdAutomationsRoute
  EmbedAccountAccountIdConversationsRoute: typeof EmbedAccountAccountIdConversationsRoute
  EmbedAccountAccountIdFollowupRoute: typeof EmbedAccountAccountIdFollowupRoute
  EmbedAccountAccountIdIntegrationsRoute: typeof EmbedAccountAccountIdIntegrationsRoute
  EmbedAccountAccountIdLogsRoute: typeof EmbedAccountAccountIdLogsRoute
  EmbedAccountAccountIdMainAgentRoute: typeof EmbedAccountAccountIdMainAgentRoute
  EmbedAccountAccountIdMediaRoute: typeof EmbedAccountAccountIdMediaRoute
  EmbedAccountAccountIdOverviewRoute: typeof EmbedAccountAccountIdOverviewRoute
  EmbedAccountAccountIdWarmupRoute: typeof EmbedAccountAccountIdWarmupRoute
  EmbedAccountAccountIdIndexRoute: typeof EmbedAccountAccountIdIndexRoute
}

const EmbedAccountAccountIdRouteChildren: EmbedAccountAccountIdRouteChildren = {
  EmbedAccountAccountIdAutomationsRoute: EmbedAccountAccountIdAutomationsRoute,
  EmbedAccountAccountIdConversationsRoute:
    EmbedAccountAccountIdConversationsRoute,
  EmbedAccountAccountIdFollowupRoute: EmbedAccountAccountIdFollowupRoute,
  EmbedAccountAccountIdIntegrationsRoute:
    EmbedAccountAccountIdIntegrationsRoute,
  EmbedAccountAccountIdLogsRoute: EmbedAccountAccountIdLogsRoute,
  EmbedAccountAccountIdMainAgentRoute: EmbedAccountAccountIdMainAgentRoute,
  EmbedAccountAccountIdMediaRoute: EmbedAccountAccountIdMediaRoute,
  EmbedAccountAccountIdOverviewRoute: EmbedAccountAccountIdOverviewRoute,
  EmbedAccountAccountIdWarmupRoute: EmbedAccountAccountIdWarmupRoute,
  EmbedAccountAccountIdIndexRoute: EmbedAccountAccountIdIndexRoute,
}

const EmbedAccountAccountIdRouteWithChildren =
  EmbedAccountAccountIdRoute._addFileChildren(
    EmbedAccountAccountIdRouteChildren,
  )

interface EmbedRouteChildren {
  EmbedAccountAccountIdRoute: typeof EmbedAccountAccountIdRouteWithChildren
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedAccountAccountIdRoute: EmbedAccountAccountIdRouteWithChildren,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmbedRoute: EmbedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
