// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjpysrdegkllabfcqjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZranB5c3JkZWdrbGxhYmZjcWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3Mzk2MjYsImV4cCI6MjA5MzMxNTYyNn0.wLy2BW2pCFOgFKBIivaAcg9OGG0eq6m-6MwgOxGnfFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});